/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/smartphone.glb src/components/Smartphone.jsx 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Phone(props) {
  const { nodes, materials } = useGLTF("/models/smartphone.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={
          nodes["tripo_node_197926cc-33e1-47c2-b21d-897f445a8b0f"].geometry
        }
        material={materials["tripo_mat_197926cc-33e1-47c2-b21d-897f445a8b0f"]}
      />
    </group>
  );
}

useGLTF.preload("/models/smartphone.glb");
