/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/textured.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Abhi(props) {
  const { nodes, materials } = useGLTF("/models/textured.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.textured_mesh.geometry}
        material={materials["Material.018"]}
        rotation={[Math.PI / 1.5, 0, 0]}
        scale={[3, 3, 3]}
      />
    </group>
  );
}

useGLTF.preload("/models/textured.glb");
